[gauntlet]
name = 'Dev Plugin'
description = """
A reasonably long plugin description that doesn't contain any usefull information
"""

[[preferences]]
name = 'testBool'
type = 'bool'
default = true
description = "test bool description"


[[entrypoint]]
id = 'detail-view'
name = 'Detail view'
path = 'src/detail-view.tsx'
type = 'view'
description = """
A reasonably long detail description that tries to tell something usefull
"""

[[entrypoint.actions]]
id = 'testAction1'
description = "test action description 1"
shortcut = { key = 'a', kind = 'main'}

[[entrypoint.actions]]
id = 'testAction2'
description = "test action description 2"
shortcut = { key = 'B', kind = 'main'}

[[entrypoint.preferences]]
name = 'testBool'
type = 'bool'
default = true
description = "test bool description"

[[entrypoint.preferences]]
name = 'testEnum'
type = 'enum'
default = 'item'
enum_values = [{ label = 'Item', value = 'item'}, { label = 'Item 2', value = 'item_2'}]
description = "test enum description"

[[entrypoint.preferences]]
name = 'testListOfStrings'
type = 'list_of_strings'
description = "test list of strings description"

[[entrypoint.preferences]]
name = 'testListOfNumbers'
type = 'list_of_numbers'
description = "test list of numbers description"

[[entrypoint.preferences]]
name = 'testListOfEnums'
type = 'list_of_enums'
description = "test list of enums description"
enum_values = [{ label = 'Item', value = 'item'}, { label = 'Item 2', value = 'item_2'}]

[[entrypoint.preferences]]
name = 'testNum'
type = 'number'
default = 2
description = "test number description"

[[entrypoint.preferences]]
name = 'testStr'
type = 'string'
default = 'test_value'
description = "test string description"




[[entrypoint]]
id = 'form-view'
name = 'Form view'
path = 'src/form-view.tsx'
type = 'view'
description = ''

[[entrypoint.actions]]
id = 'testAction'
description = "test action description in form"
shortcut = { key = ':', kind = 'main'}

[[entrypoint]]
id = 'inline-view'
name = 'Inline view'
path = 'src/inline-view.tsx'
type = 'inline-view'
description = ''

[[entrypoint]]
id = 'grid-view'
name = 'Grid view'
path = 'src/grid-view.tsx'
type = 'view'
description = ''

[[entrypoint]]
id = 'list-view'
name = 'List view'
path = 'src/list-view.tsx'
type = 'view'
description = ''

[[entrypoint]]
id = 'hooks-view'
name = 'Hooks view'
path = 'src/hooks-view.tsx'
type = 'view'
description = ''

[[entrypoint]]
id = 'command-a'
name = 'Command A'
path = 'src/command-a.ts'
type = 'command'
description = ''

[[entrypoint]]
id = 'command-generator'
name = 'Command generator'
path = 'src/command-generator.ts'
type = 'command-generator'
description = ''

[[entrypoint]]
id = 'test-list-detail'
name = 'Test List Detail'
path = 'src/test-list-detail.tsx'
type = 'view'
description = ''

[[supported_system]]
os = 'linux'

[[supported_system]]
os = 'macos'

[[supported_system]]
os = 'windows'

[permissions]
environment = ["RUST_LOG"]
system = ["systemMemoryInfo"]
network = ["upload.wikimedia.org"]