[gauntlet]
name = 'Dev Plugin'
description = """
A reasonably long plugin description that doesn't contain any usefull information
"""

[[preferences]]
id = 'testBool'
name = 'Test Boolean'
type = 'bool'
default = true
description = "test bool description"


[[entrypoint]]
id = 'detail-view'
name = 'Detail view'
path = 'src/detail-view.tsx'
type = 'view'
description = """
A reasonably long detail description that tries to tell something usefull
"""

[[entrypoint.actions]]
id = 'testAction1'
description = "test action description 1"
shortcut = { key = 'a', kind = 'main'}

[[entrypoint.actions]]
id = 'testAction2'
description = "test action description 2"
shortcut = { key = 'B', kind = 'main'}

[[entrypoint.preferences]]
id = 'testBool'
name = 'Test Boolean'
type = 'bool'
default = true
description = "test bool description"

[[entrypoint.preferences]]
id = 'testEnum'
name = 'Test Enum'
type = 'enum'
default = 'item'
enum_values = [{ label = 'Item', value = 'item'}, { label = 'Item 2', value = 'item_2'}]
description = "test enum description"

[[entrypoint.preferences]]
id = 'testListOfStrings'
name = 'Test List of Strings'
type = 'list_of_strings'
description = "test list of strings description"

[[entrypoint.preferences]]
id = 'testListOfNumbers'
name = 'Test List of Numbers'
type = 'list_of_numbers'
description = "test list of numbers description"

[[entrypoint.preferences]]
id = 'testListOfEnums'
name = 'Test List of Enums'
type = 'list_of_enums'
description = "test list of enums description"
enum_values = [{ label = 'Item', value = 'item'}, { label = 'Item 2', value = 'item_2'}]

[[entrypoint.preferences]]
id = 'testNum'
name = 'Test Num'
type = 'number'
default = 2
description = "test number description"

[[entrypoint.preferences]]
id = 'testStr'
name = 'Test Str'
type = 'string'
default = 'test_value'
description = "test string description"




[[entrypoint]]
id = 'form-view'
name = 'Form view'
path = 'src/form-view.tsx'
type = 'view'
description = ''

[[entrypoint.actions]]
id = 'testAction'
description = "test action description in form"
shortcut = { key = ':', kind = 'main'}

[[entrypoint]]
id = 'inline-view'
name = 'Inline view'
path = 'src/inline-view.tsx'
type = 'inline-view'
description = ''

[[entrypoint]]
id = 'grid-view'
name = 'Grid view'
path = 'src/grid-view.tsx'
type = 'view'
description = ''

[[entrypoint]]
id = 'list-view'
name = 'List view'
path = 'src/list-view.tsx'
type = 'view'
description = ''

[[entrypoint]]
id = 'hooks-view'
name = 'Hooks view'
path = 'src/hooks-view.tsx'
type = 'view'
description = ''

[[entrypoint]]
id = 'command-a'
name = 'Command A'
path = 'src/command-a.ts'
type = 'command'
description = ''

[[entrypoint]]
id = 'command-generator'
name = 'Command generator'
path = 'src/command-generator.ts'
type = 'command-generator'
description = ''

[[entrypoint.actions]]
id = 'testGeneratedAction1'
description = "test action description 1"
shortcut = { key = 'a', kind = 'main'}


[[entrypoint]]
id = 'test-list-detail'
name = 'Test List Detail'
path = 'src/test-list-detail.tsx'
type = 'view'
description = ''

[[supported_system]]
os = 'linux'

[[supported_system]]
os = 'macos'

[[supported_system]]
os = 'windows'

[permissions]
environment = ["RUST_LOG"]
system = ["systemMemoryInfo"]
network = ["upload.wikimedia.org", "api.github.com"]
clipboard = ["read", "write", "clear"]
main_search_bar = ["read"]

[permissions.filesystem]
read = [
    "C:\\ProgramFiles\\test",
    "C:/ProgramFiles/test",
    "{windows:user-home}\\test",
    "{windows:user-home}/test",
    "{linux:user-home}/test",
    "/etc/test"
]
write = ["/home/exidex/.test"]

[permissions.exec]
command = ["ls"]
executable = ["/usr/bin/ls"]