[package]
name = "gauntlet-scenario-runner"
edition.workspace = true

[dependencies]
# workspaces
gauntlet-common.workspace = true
gauntlet-utils.workspace = true

# shared
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

