[package]
name = "placeholdername"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
deno_core = { version = "0.204.0" }
deno_runtime = { version = "0.126.0" }
tokio = "1.28.1"
#taffy = "0.3.12"
relm4 = "0.6.0"
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_10"] }
#gtk-layer-shell = { version = "0.0.3", package = "gtk4-layer-shell" }
directories = "5.0"
toml = "0.7.6"
serde_json = "1.0"
tantivy = "0.20.2"
regex = "1.9.3"
once_cell = "1.18.0"
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
clap = { version = "4.3.22", features = ["derive"] }
gix = { version = "0.52.0", features = ["blocking-network-client"] }
tempfile = "3"
futures-concurrency = "7.4.2"