[package]
name = "placeholdername"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "rust/management_client",
    "rust/client",
    "rust/server",
    "rust/common",
    "rust/utils",
    "rust/cli",
]

[dependencies]
cli = { path = "rust/cli" }

[features]
dev = ["cli/dev"]
