[package]
name = "gauntlet"
edition = "2021"
repository = "https://github.com/project-gauntlet/gauntlet"

[workspace]
members = [
    "rust/management_client",
    "rust/client",
    "rust/server",
    "rust/common",
    "rust/utils",
    "rust/cli",
    "rust/component_model",
]

[dependencies]
cli = { path = "rust/cli" }

[features]
dev = ["cli/dev"]
