[package]
name = "component_model"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
anyhow = "1.0.75"
indexmap = { version = "2.1.0", features = ["serde"] }
