[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.28.1"
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
anyhow = "1"
thiserror = "1"
iced = { version = "0.10", features = ["tokio", "lazy", "advanced"] }
iced_aw = { version = "0.7.0", default-features = false, features = ["icons", "date_picker"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
common = { path = "../common" }
utils = { path = "../utils" }

[build-dependencies]
component_model = { path = "../component_model" }
anyhow = "1"
convert_case = "0.6.0"
