[package]
name = "client"
edition = "2021"

[dependencies]
tokio = "1.28.1"
anyhow = "1"
thiserror = "1"
iced = { version = "0.10", features = ["tokio", "lazy", "advanced"] }
iced_aw = { version = "0.7.0", default-features = false, features = ["icons", "date_picker", "floating_element", "wrap"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
common = { path = "../common" }
utils = { path = "../utils" }
tonic = "0.11.0"

[build-dependencies]
component_model = { path = "../component_model" }
anyhow = "1"
convert_case = "0.6.0"
