[package]
name = "client"
edition = "2021"

[dependencies]
tokio = "1.28.1"
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1"
iced_aw.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
common = { path = "../common" }
common-ui = { path = "../common_ui" }
utils = { path = "../utils" }
tonic = "0.11.0"
itertools = "0.12.1"
component_model = { path = "../component_model" }
strum = { version = "0.26", features = ["derive"] }
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
bytes = "1.6.0"

[target.'cfg(target_os = "linux")'.dependencies]
iced.workspace = true
iced.features = ["wayland"]

[target.'cfg(not(target_os = "linux"))'.dependencies]
iced.workspace = true

[build-dependencies]
component_model = { path = "../component_model" }
anyhow = { version = "1", features = ["backtrace"] }
convert_case = "0.6.0"

[features]
scenario_runner = []
