[package]
name = "client"
edition = "2021"

[dependencies]
tokio = "1.28.1"
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1"
#iced = { version = "0.12.0", features = ["tokio", "lazy", "advanced"] }
iced = { git = "https://github.com/project-gauntlet/iced.git", branch = "gauntlet", features = ["tokio", "lazy", "advanced", "multi-window", "image"] }
#iced_aw = { git = "https://github.com/iced-rs/iced_aw.git", rev = "687fe55689517c82d289af311bc6a17d9d08c01a", default-features = false, features = ["icons", "date_picker", "floating_element", "wrap"] }
iced_aw = { git = "https://github.com/project-gauntlet/iced_aw.git", branch = "gauntlet", default-features = false, features = ["icons", "date_picker", "floating_element", "wrap", "grid"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
common = { path = "../common" }
common-ui = { path = "../common_ui" }
utils = { path = "../utils" }
tonic = "0.11.0"
global-hotkey = "0.4.2"
itertools = "0.12.1"
component_model = { path = "../component_model" }
strum = { version = "0.26", features = ["derive"] }
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"

[build-dependencies]
component_model = { path = "../component_model" }
anyhow = { version = "1", features = ["backtrace"] }
convert_case = "0.6.0"

[features]
scenario_runner = []
