[package]
name = "server"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
deno_core = { version = "0.204.0" }
deno_runtime = { version = "0.126.0" }
tokio = "1.28.1"
directories = "5.0"
toml = "0.8.10"
tantivy = "0.20.2"
zstd-sys = "=2.0.9" # TODO REMOVE https://github.com/gyscos/zstd-rs/issues/270
regex = "1.9.3"
once_cell = "1.18.0"
gix = { version = "0.52.0", features = ["blocking-http-transport-curl"] }
tempfile = "3"
async-stream = "0.3.5"
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1.0.48"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "json", "sqlite" ] }
common = { path = "../common" }
utils = { path = "../utils" }
component_model = { path = "../component_model" }
tonic = "0.11.0"
client = { path = "../client" }
walkdir = "2.4.0"
include_dir = "0.7.3"

[features]
dev = []
