[package]
name = "management_client"
edition = "2021"

[dependencies]
tokio = "1.28.1"
clap = { version = "4.3.22", features = ["derive"] }
anyhow = "1.0.75"
thiserror = "1.0.48"
iced = { version = "0.10", features = ["tokio", "lazy", "advanced"] }
iced_table = "0.1.0"
iced_aw = { version = "0.7.0", default-features = false, features = ["icons"] }
tracing = "0.1"
tracing-subscriber = "0.3"
common = { path = "../common" }
tonic = "0.11.0"