[package]
name = "common_plugin_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.94"
common = { path = "../common" }
bytes = "1.6.0"
serde-value = "0.7.0"
