[package]
name = "plugin_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = { version = "0.321.0" } # deno 2.1.1
deno_runtime = { version = "0.188.0" }
tokio = "1.28.1"
anyhow = { version = "1", features = ["backtrace"] }
regex = "1.9.3"
once_cell = "1.18.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
common = { path = "../common" }
typed-path = "0.9"
indexmap = { version = "2.1.0", features = ["serde"] }
component_model = { path = "../component_model" }
bytes = "1.6.0"
image = "0.25"
resvg = { version = "0.41", default-features = false}
walkdir = "2.4.0"
numbat = "1.14.0"
interprocess = { version = "2.2.2", features = ["tokio"] }
tokio-util = "0.7.11"
bincode = "2.0.0-rc.3"
utils = { path = "../utils" }
futures = "0.3.31"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2.153"

[target.'cfg(target_os = "linux")'.dependencies]
freedesktop_entry_parser = "1.3"
freedesktop-icons = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
cacao = "0.3.2"
plist = "1.6.1"
icns = "0.3.1"
objc2-app-kit = { version = "0.2.2", features = ["NSWorkspace", "NSImage", "NSImageRep", "NSBitmapImageRep", "NSGraphics", "NSGraphicsContext"] }
objc2-foundation = { version = "0.2.2", features = ["NSString"] }
objc2 = "0.5.2"

[features]
scenario_runner = []
