[metadata]
name='Interesting Plugin Name'

[[entrypoints]]
id='detail-view'
name='Detail view'
path='src/detail-view.tsx'

[[entrypoints]]
id='form-view'
name='Form view'
path='src/form-view.tsx'

[permissions]
environment=["RUST_LOG"]