[metadata]
name='Interesting Plugin Name'

[[entrypoint]]
id='detail-view'
name='Detail view'
path='src/detail-view.tsx'

[[entrypoint]]
id='form-view'
name='Form view'
path='src/form-view.tsx'

[[supported_system]]
os='linux'

[permissions]
environment=["RUST_LOG"]