[gauntlet]
name = 'Calculator'
description = ''

[[entrypoint]]
id = 'default'
name = 'Default'
path = 'src/default.tsx'
type = 'inline-view'
description = ''

[permissions]
main_search_bar = ["read"]
