[package]
name = "common"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
gix = { version = "0.52.0", features = ["blocking-http-transport-curl"] }
anyhow = "1.0.75"
