[package]
name = "common"
edition = "2021"

[dependencies]
gix-url = { version = "0.22.0" }
anyhow = { version = "1", features = ["backtrace"] }
tonic = "0.11.0"
prost = "0.12.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.11.0"
