[gauntlet]
name = 'Applications'
description = 'Run applications from your system as commands'

[[entrypoint]]
id = 'default'
name = 'Default'
path = 'src/default.ts'
type = 'command-generator'
description = ''

[[supported_system]]
os = 'linux'

[[supported_system]]
os = 'macos'

[[supported_system]]
os = 'windows'
