name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-linux.yaml
      - run: npm run build-linux-project --workspace @project-gauntlet/build

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/setup-macos.yaml
      - run: npm run build-macos-project --workspace @project-gauntlet/build
