name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y protobuf-compiler # deno_kv needs this

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - run: npm ci

      - run: npm run build --workspace @project-gauntlet/api
      - run: npm run build --workspace @project-gauntlet/tools
      - run: npm run build --workspace @project-gauntlet/deno
      - run: npm run build --workspace @project-gauntlet/react

      - run: npm run build --workspace @project-gauntlet/react-renderer
      - run: npm run build --workspace @project-gauntlet/core

      - run: |
          cargo check
          cargo build --release