name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    uses: ./.github/workflows/setup-linux.yaml
    with:
      command: npm run build-linux-project --workspace @project-gauntlet/build

  build-macos:
    uses: ./.github/workflows/setup-macos.yaml
    with:
      command: npm run build-macos-project --workspace @project-gauntlet/build
