name: release

on: workflow_dispatch

jobs:
  publish-init:
    uses: ./.github/workflows/setup-linux.yaml
    with:
      command: npm run publish-init-project --workspace @project-gauntlet/build

  publish-linux:
    needs:
      - publish-init
    uses: ./.github/workflows/setup-linux.yaml
    with:
      command: npm run publish-linux-project --workspace @project-gauntlet/build

  publish-macos:
    needs:
      - publish-init
    uses: ./.github/workflows/setup-macos.yaml
    with:
      command: npm run publish-macos-project --workspace @project-gauntlet/build

  publish-final:
    runs-on: ubuntu-latest
    needs:
      - publish-linux
      - publish-macos
    uses: ./.github/workflows/setup-linux.yaml
    with:
      command: npm run publish-final-project --workspace @project-gauntlet/buil